673 HW1 Q4

In [169]:
import sympy as sp
import numpy as np
import math as ma
from numpy.linalg import eig

storing the given data in matrix form

In [170]:
val = sp.Matrix([[5, 5, 100, 100],[150, 5, 200, 80], [150 ,150 ,220, 80], [5, 150, 100, 200]])

In [171]:
val

Matrix([
[  5,   5, 100, 100],
[150,   5, 200,  80],
[150, 150, 220,  80],
[  5, 150, 100, 200]])

Creating A matrix out of given data

In [172]:
A = np.matrix([[-val[0,0], -val[0,1], -1, 0, 0, 0, val[0,0]*val[0,2], val[0,1]*val[0,2], val[0,2]],
               [0, 0, 0, -val[0,0], -val[0,1], -1, val[0,0]*val[0,3], val[0,1]*val[0,3], val[0,3]],
               [-val[1,0], -val[1,1], -1, 0, 0, 0, val[1,0]*val[1,2], val[1,1]*val[1,2], val[1,2]],
               [0, 0, 0, -val[1,0], -val[1,1], -1, val[1,0]*val[1,3], val[1,1]*val[1,3], val[1,3]],
               [-val[2,0], -val[2,1], -1, 0, 0, 0, val[2,0]*val[2,2], val[2,1]*val[2,2], val[2,2]],
               [0, 0, 0, -val[2,0], -val[2,1], -1, val[2,0]*val[2,3], val[2,1]*val[2,3], val[2,3]],
               [-val[3,0], -val[3,1], -1, 0, 0, 0, val[3,0]*val[3,2], val[3,1]*val[3,2], val[3,2]],
               [0, 0, 0, -val[3,0], -val[3,1], -1, val[3,0]*val[3,3], val[3,1]*val[3,3], val[3,3]],                         
               ], dtype = 'float')

Given matrix A (m = 8, n= 9)

In [173]:
A

matrix([[-5.0e+00, -5.0e+00, -1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
          5.0e+02,  5.0e+02,  1.0e+02],
        [ 0.0e+00,  0.0e+00,  0.0e+00, -5.0e+00, -5.0e+00, -1.0e+00,
          5.0e+02,  5.0e+02,  1.0e+02],
        [-1.5e+02, -5.0e+00, -1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
          3.0e+04,  1.0e+03,  2.0e+02],
        [ 0.0e+00,  0.0e+00,  0.0e+00, -1.5e+02, -5.0e+00, -1.0e+00,
          1.2e+04,  4.0e+02,  8.0e+01],
        [-1.5e+02, -1.5e+02, -1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
          3.3e+04,  3.3e+04,  2.2e+02],
        [ 0.0e+00,  0.0e+00,  0.0e+00, -1.5e+02, -1.5e+02, -1.0e+00,
          1.2e+04,  1.2e+04,  8.0e+01],
        [-5.0e+00, -1.5e+02, -1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
          5.0e+02,  1.5e+04,  1.0e+02],
        [ 0.0e+00,  0.0e+00,  0.0e+00, -5.0e+00, -1.5e+02, -1.0e+00,
          1.0e+03,  3.0e+04,  2.0e+02]])

Creating an empty x matrix

In [174]:
x = np.empty((9, 1))

Finding $A*A^T$ $(8*8)$ for U and $A^T*A$ $(9*9)$ for $V^T$

In [180]:
W_U = np.array((A*A.T), dtype = float)

W_V = np.array((A.T*A), dtype = float)


Finding U and V

In [274]:
eig_U, U  = eig(W_U)
eig_V, V = eig(W_V)

In [275]:
eig_U

array([3.62583363e+09, 1.01280011e+09, 6.80651927e+04, 3.46776193e+04,
       2.12012335e+04, 3.70648899e+03, 6.56490977e-01, 1.52001454e+01])

Sorting the eigen values and vector using sort and flip function

In [277]:
# dict_U = {}
# for i in range(len(eig_U)):
#     dict_U[i] = {eig_U[i]:U[:,i]}
indx = np.argsort(eig_U)
indx = np.flip(indx)
eig_U = eig_U[indx]
U = U[:, indx]

In [278]:
eig_U

array([3.62583363e+09, 1.01280011e+09, 6.80651927e+04, 3.46776193e+04,
       2.12012335e+04, 3.70648899e+03, 1.52001454e+01, 6.56490977e-01])

eigen values and vectors of $A*A^T$

In [280]:

V_T = V.T


Displaying U

In [281]:
U

array([[ 1.17519867e-02,  3.44207228e-04, -5.15532162e-02,
        -4.66128587e-01, -2.60345896e-01, -6.78428560e-02,
         1.08122912e-02, -8.41087769e-01],
       [ 1.17517760e-02,  3.43641967e-04, -8.72103737e-02,
        -4.59351955e-01, -2.49098952e-01, -8.85591890e-02,
         7.65455994e-01,  3.54169473e-01],
       [ 3.58735699e-01,  6.54942912e-01,  1.34538659e-02,
        -4.65084492e-01,  1.70101644e-01,  2.93617516e-01,
        -2.78385484e-01,  1.82289868e-01],
       [ 1.43494223e-01,  2.61976394e-01, -4.45383120e-01,
         1.36060221e-01, -5.00795526e-01, -5.87488150e-01,
        -2.73099286e-01,  1.52897235e-01],
       [ 7.74962678e-01,  2.27117371e-02,  4.08516159e-01,
         2.84937362e-01,  3.19642679e-02, -2.35211438e-01,
         2.62688692e-01, -1.59658350e-01],
       [ 2.81806634e-01,  8.24745878e-03, -6.92167142e-01,
         3.15915567e-01,  1.14149714e-02,  5.01908806e-01,
         2.46628160e-01, -1.69560615e-01],
       [ 1.84643411e-01, -3.168062

Displaying $V^T$

In [282]:
V_T

array([[ 2.84043894e-03,  2.42121739e-03,  2.20891154e-05,
         1.09109680e-03,  1.63479471e-03,  1.33908907e-05,
        -6.96053715e-01, -7.17950893e-01, -6.16016024e-03],
       [ 3.14430147e-03, -1.28321626e-03,  1.13495064e-05,
         1.17416448e-03, -2.90636016e-03, -1.14077892e-05,
        -7.17961695e-01,  6.96067270e-01,  2.29933343e-05],
       [-2.46384735e-01, -3.77000733e-01, -2.37217168e-03,
         6.61240940e-01,  5.74279813e-01,  5.80190908e-03,
        -7.57487349e-05,  1.62813209e-03, -1.73453679e-01],
       [-1.58554932e-01,  1.76600215e-01, -3.65660431e-03,
         3.41172744e-01, -7.10405325e-02, -2.15181510e-03,
        -3.79564118e-03, -3.77529395e-03,  9.06741660e-01],
       [-1.75245114e-01,  6.89508147e-01,  5.19584361e-03,
         5.01749740e-01, -3.14549320e-01,  2.88147957e-03,
         2.50334194e-03,  2.49754245e-03, -3.78319687e-01],
       [ 1.76705635e-01,  5.90273326e-01,  7.52000216e-03,
        -2.32499365e-01,  7.49883366e-01, -5.735047

Displaying singular values $\sigma^2$ (already sorted)

In [283]:
eig_V

array([ 3.62583363e+09,  1.01280011e+09,  6.80651927e+04,  3.46776193e+04,
        2.12012335e+04,  3.70648899e+03,  1.52001454e+01,  6.56490976e-01,
       -1.47199605e-10])

Creating $\Sigma$ Matrix

singular values $σ_i$= $sqrt(Λ_i)$
$Σ$ = diagonal(σ_i)

In [284]:

sigma = np.zeros((9,9))
j = 0
S = [] #to be used for storing sigma values
for i in eig_V[0:8]:
  S.append(ma.sqrt(i))
  j = j+1
S.append(0)

In [285]:
sigma = np.diag((S))
# sigma = sp.Matrix(sigma)
sigma_mn = sigma[0:8,:]

In [286]:
sigma_mn

array([[6.02148954e+04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 3.18245207e+04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.60893068e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.86219278e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.45606434e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 6.08809411e+01, 0.00000000e+00, 0.00000000e+00,
        0.0

In [287]:
A = np.dot(U,np.dot(sigma_mn,V_T))

Displaying SVD of A

In [288]:

u,s,vh = np.linalg.svd(A, full_matrices=True)

Printing the difference between singular values

In [290]:
print('sigma matrix difference between manual and inbuilt function \n', (np.sqrt(eig_V[:8]) - s).round(3))

sigma matrix difference between manual and inbuilt function 
 [-0.  0.  0.  0. -0.  0. -0. -0.]


Printing the difference between U matrix

In [292]:
print('U matrix difference between manual and inbuilt function  \n', (U - u).round(4))
# print('U matrix using inbuilt function', u.round(5))

U matrix difference between manual and inbuilt function  
 [[ 0.0235  0.     -0.1031 -0.     -0.5207 -0.      0.     -1.6822]
 [ 0.0235 -0.     -0.1744 -0.     -0.4982  0.     -0.      0.7083]
 [ 0.7175 -0.      0.0269  0.      0.3402 -0.     -0.      0.3646]
 [ 0.287   0.     -0.8908  0.     -1.0016  0.     -0.      0.3058]
 [ 1.5499  0.      0.817  -0.      0.0639  0.      0.     -0.3193]
 [ 0.5636 -0.     -1.3843  0.      0.0228  0.      0.     -0.3391]
 [ 0.3693 -0.      0.4969 -0.     -1.3965  0.     -0.      0.3633]
 [ 0.7386 -0.     -0.5778  0.      0.6378 -0.     -0.      0.3053]]


In [293]:
print('V matrix difference between manual and inbuilt function  \n', V_T.round(3) - vh.round(3))

V matrix difference between manual and inbuilt function  
 [[ 0.006  0.004  0.     0.002  0.004  0.    -1.392 -1.436 -0.012]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [-0.492 -0.754 -0.004  1.322  1.148  0.012 -0.     0.004 -0.346]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [-0.35   1.38   0.01   1.004 -0.63   0.006  0.006  0.004 -0.756]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [-0.24  -0.004  1.572 -0.086  0.01  -1.21  -0.002  0.    -0.004]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]


Homogeniety matrix is given by the eigen vector of V corresponding to smallest eigen value. H is the last column of V?

In [195]:
i = np.argmin(eig_V)

In [196]:
H = V[:,i]

In [254]:
H_1 = np.zeros((3,3))
k = 0
for i in range(3):
    for j in range(3):
        H_1[i,j] = H[k]
        k  = k + 1

In [255]:
H_1

array([[ 5.31056349e-02, -4.91718842e-03,  6.14648552e-01],
       [ 1.77018783e-02, -3.93375074e-03,  7.86750146e-01],
       [ 2.36025044e-04, -4.91718842e-05,  7.62164204e-03]])